### ISSUE TITLE
Team 21 pandabears peer to peer code review

### ISSUE THREAD

**Issue by rsundar** [rsundar/micro-reddit#11]

**Comment by emmanuelkamala** [comment]
I have cloned the app, and it works fine. The design looks good, didn't get errors on my end. Maybe just for easier viewing of the app, you can add a live link on the Read me file. 
Otherwise, great work mate!

**Comment by emmanuelkamala** [comment]
I have cloned the app, the model works fine, didn't get errors on my end. Great work @rsundar!

**Comment by Mesi21** [comment]
It has all the models the project asks for. Congrats @rsundar!

**Comment by grace-mugoiri** [comment]
Well structured.

**Comment by rsundar** [comment]
thanks all!
